scikit-learnの復習

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame(
    {
        'A': [1, np.nan, 3, 4, 5],
        'B': [6, 7, 8, np.nan, 10],
        'C': [11, 12, 13, 14, 15]
    }
)
df

,A,B,C
0,1.0,6.0,11
1,NaN,7.0,12
2,3.0,8.0,13
3,4.0,NaN,14
4,5.0,10.0,15


In [ ]:
df.isnull()  #欠損値かどうかを確かめる

,A,B,C
0,False,False,False
1,True,False,False
2,False,False,False
3,False,True,False
4,False,False,False


In [5]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='mean')  #平均値で欠損値を埋めるインスタンス
imp.fit_transform(df)


array([[ 1.  ,  6.  , 11.  ],
       [ 3.25,  7.  , 12.  ],
       [ 3.  ,  8.  , 13.  ],
       [ 4.  ,  7.75, 14.  ],
       [ 5.  , 10.  , 15.  ]])

In [7]:
df = pd.DataFrame(
    {
        'A': [1, 2, 3, 4, 5],
        'B': ['a', 'b', 'a', 'b', 'c']  #カテゴリ変数
    }
)
df

,A,B
0,1,a
1,2,b
2,3,a
3,4,b
4,5,c


In [ ]:
#カテゴリ変数のエンコーディング
#a=0, b=1, c=2　のようにカテゴリを数字に変換する
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(df.loc[:, 'B'])

array([0, 1, 0, 1, 2])

In [9]:
le.classes_

array(['a', 'b', 'c'], dtype=object)

In [10]:
df = pd.DataFrame(
    {
        'A': [1, 2, 3, 4,5],
        'B': [100, 200, 400, 500, 800]
    }
)
df

,A,B
0,1,100
1,2,200
2,3,400
3,4,500
4,5,800


In [11]:
#データの標準化
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
stdsc.fit_transform(df)

array([[-1.41421356, -1.22474487],
       [-0.70710678, -0.81649658],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.40824829],
       [ 1.41421356,  1.63299316]])