##教科書の復習

In [2]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1, 2, 3],
             [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.shape

(2, 3)

In [6]:
c1 = np.array([0, 1, 2, 3, 4, 5])
print(c1)
c2 = c1.reshape((2, 3))
c2

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
a

array([1, 2, 3])

In [8]:
a[0]

np.int64(1)

In [9]:
b[0]

array([1, 2, 3])

In [10]:
b[0,0]

np.int64(1)

In [11]:
b[:, 1]

array([2, 5])

In [3]:
import numpy as np
a = np.array([1, 2, 3])
a1 = a
a1

array([1, 2, 3])

In [4]:
a1[1] = 5
print(a1)
print(a)

[1 5 3]
[1 5 3]


In [5]:
a2 = a.copy()
print(a2)
a2[0] = 6
print(a2, a)

[1 5 3]
[6 5 3] [1 5 3]


In [6]:
c2 = np.array([[0, 1, 2],
               [3, 4, 5]])
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7
print(c3)
print(c4)

[6 1 2 3 4 5]
[0 7 2 3 4 5]


In [ ]:
c2  # ravelは参照　flatten はコピー

array([[6, 1, 2],
       [3, 4, 5]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
rng = np.random.default_rng(123)
f = rng.random((3, 2))
f

array([[0.68235186, 0.05382102],
       [0.22035987, 0.18437181],
       [0.1759059 , 0.81209451]])

In [10]:
rng.integers(1, 10)

np.int64(5)

In [11]:
rng.integers(1, 10, size=(3, 3))


array([[9, 5, 3],
       [8, 8, 8],
       [9, 1, 5]])

In [12]:
rng = np.random.default_rng(123)
rng.standard_normal(size=(4, 2))


array([[-0.98912135, -0.36778665],
       [ 1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379],
       [-0.63646365,  0.54195222]])

In [13]:
rng.normal(50, 10, 3)

array([46.83404549, 46.77610884, 50.97167319])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.nan

nan

In [16]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [19]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [21]:
a

array([1, 5, 3])

In [22]:
a1

array([1, 5, 3])

In [23]:
np.concatenate([a, a1])

array([1, 5, 3, 1, 5, 3])

In [25]:
b = np.array([[1, 2, 8],
              [4, 5, 8]])

In [26]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [27]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [28]:
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [29]:
b2 = np.array([30, 60, 45])
np.vstack([b, b2])

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [30]:
b3 = np.vstack([b, b2])
first, second = np.hsplit(b3, [2])
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [31]:
second

array([[ 8],
       [ 8],
       [45]])

In [32]:
first1, second1 = np.vsplit(b3, [2])
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [33]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [34]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [35]:
print(a)
a[np.newaxis, :]

[1 5 3]


array([[1, 5, 3]])

In [37]:
a[:, np.newaxis]

array([[1],
       [5],
       [3]])

In [38]:
m = np.arange(0, 4)
n = np.arange(4, 7)
xx, yy = np.meshgrid(m, n)
print(xx)
print(yy)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


In [39]:
li = [[-3, -2, -1],
      [0, 1, 2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))

new

[[3, 2, 1], [0, 1, 2]]

In [41]:
b = np.array([[-3, -2, -1],
             [0, 1, 2]])
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [43]:
e = np.linspace(-1, 1, 10)
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [44]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [45]:
a = np.arange(3)
np.log(a)

C:\Users\shige\AppData\Local\Temp\ipykernel_25400\1924608818.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [46]:
np.log10(a)

C:\Users\shige\AppData\Local\Temp\ipykernel_25400\547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([   -inf, 0.     , 0.30103])

In [47]:
a +10

array([10, 11, 12])

In [48]:
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [49]:
a1

array([1, 5, 3])

In [50]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [51]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [54]:
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c - np.mean(c))
print((c - np.mean(c))**2)

[[-2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5]]
[[6.25 2.25 0.25]
 [0.25 2.25 6.25]]


In [55]:
c/a

C:\Users\shige\AppData\Local\Temp\ipykernel_25400\1041459248.py:1: RuntimeWarning: divide by zero encountered in divide
  c/a


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [56]:
c/(a+1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

In [57]:
np.dot(b, a)

array([-4,  5])

In [58]:
a > 1

array([False, False,  True])

In [59]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [60]:
np.count_nonzero(b>0)

np.int64(2)

In [61]:
b[b>0]

array([1, 2])

In [62]:
import pandas as pd
ser = pd.Series([10, 20, 30, 40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [63]:
df = pd.DataFrame([[10, 'a', True],
                   [20, 'b', False],
                   [40, 'd', True]])
df

,0,1,2
0,10,a,True
1,20,b,False
2,40,d,True


In [65]:
df = pd.DataFrame(np.arange(100).reshape(25, 4))
df.head()

,0,1,2,3
0,0,1,2,3
1,4,5,6,7
2,8,9,10,11
3,12,13,14,15
4,16,17,18,19


In [66]:
df = pd.DataFrame(np.arange(6).reshape((3,2)))
print(df)
df.index = ['01', '02', '03']
df.columns = ['A', 'B']
df

   0  1
0  0  1
1  2  3
2  4  5


,A,B
01,0,1
02,2,3
03,4,5


In [67]:
pd.DataFrame({'A列': [0, 2, 4], 'B列': [1, 3, 5]})

,A列,B列
0,0,1
1,2,3
2,4,5


In [68]:
df['A']

01    0
02    2
03    4
Name: A, dtype: int64

In [69]:
df[['A', 'B']]

,A,B
01,0,1
02,2,3
03,4,5


In [70]:
df[:2]

,A,B
01,0,1
02,2,3


In [72]:
df.loc[:, :]

,A,B
01,0,1
02,2,3
03,4,5


In [73]:
df.loc[:, 'A']

01    0
02    2
03    4
Name: A, dtype: int64

In [74]:
df.loc['01', :]

A    0
B    1
Name: 01, dtype: int64

In [75]:
df.iloc[1, 1]

np.int64(3)

In [76]:
df.iloc[:, 0]

01    0
02    2
03    4
Name: A, dtype: int64

In [77]:
df.iloc[1:, :]

,A,B
02,2,3
03,4,5


In [79]:
df = pd.read_excel('data/202411health.xlsx')
df

,日付,歩数,摂取カロリー
0,2024-11-01,5439,2500
1,2024-11-02,2510,2300
2,2024-11-03,10238,1950
3,2024-11-04,8209,1850
4,2024-11-05,9434,1930
5,2024-11-06,7593,1800
6,2024-11-07,9320,1940
7,2024-11-08,4873,2300
8,2024-11-09,12045,1950
9,2024-11-10,7493,1850


In [80]:
df.loc[:, '歩数'] >= 10000

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: 歩数, dtype: bool

In [82]:
df_selected = df.loc[df.loc[:, '歩数'] >= 10000, :]
df_selected

,日付,歩数,摂取カロリー
2,2024-11-03,10238,1950
8,2024-11-09,12045,1950
12,2024-11-13,10287,1800
19,2024-11-20,15328,1800
20,2024-11-21,12849,1940


In [83]:
df.query('歩数 >= 10000 and 摂取カロリー <= 1800')

,日付,歩数,摂取カロリー
12,2024-11-13,10287,1800
19,2024-11-20,15328,1800


In [ ]:
df.dtypes  #日付は文字列

日付        object
歩数         int64
摂取カロリー     int64
dtype: object

In [86]:
df['date'] = df.loc[:, '日付'].apply(pd.to_datetime) #カラムを追加、代入
df.loc[:, 'date']

0    2024-11-01
1    2024-11-02
2    2024-11-03
3    2024-11-04
4    2024-11-05
5    2024-11-06
6    2024-11-07
7    2024-11-08
8    2024-11-09
9    2024-11-10
10   2024-11-11
11   2024-11-12
12   2024-11-13
13   2024-11-14
14   2024-11-15
15   2024-11-16
16   2024-11-17
17   2024-11-18
18   2024-11-19
19   2024-11-20
20   2024-11-21
21   2024-11-22
22   2024-11-23
23   2024-11-24
24   2024-11-25
25   2024-11-26
26   2024-11-27
27   2024-11-28
28   2024-11-29
29   2024-11-30
Name: date, dtype: datetime64[ns]

In [87]:
df.dtypes

日付                object
歩数                 int64
摂取カロリー             int64
date      datetime64[ns]
dtype: object

In [88]:
df['摂取カロリー'] = df.loc[:, '摂取カロリー'].astype(np.float32)

In [90]:
df.head()

,日付,歩数,摂取カロリー,date
0,2024-11-01,5439,2500.0,2024-11-01
1,2024-11-02,2510,2300.0,2024-11-02
2,2024-11-03,10238,1950.0,2024-11-03
3,2024-11-04,8209,1850.0,2024-11-04
4,2024-11-05,9434,1930.0,2024-11-05


In [91]:
df = df.set_index('date')
df.head(9)

,日付,歩数,摂取カロリー
date,,,
2024-11-01,2024-11-01,5439,2500.0
2024-11-02,2024-11-02,2510,2300.0
2024-11-03,2024-11-03,10238,1950.0
2024-11-04,2024-11-04,8209,1850.0
2024-11-05,2024-11-05,9434,1930.0
2024-11-06,2024-11-06,7593,1800.0
2024-11-07,2024-11-07,9320,1940.0
2024-11-08,2024-11-08,4873,2300.0
2024-11-09,2024-11-09,12045,1950.0


In [93]:
df.sort_values(by='歩数').tail()

,日付,歩数,摂取カロリー
date,,,
2024-11-03,2024-11-03,10238,1950.0
2024-11-13,2024-11-13,10287,1800.0
2024-11-09,2024-11-09,12045,1950.0
2024-11-21,2024-11-21,12849,1940.0
2024-11-20,2024-11-20,15328,1800.0


In [94]:
df = df.drop('日付', axis=1)

In [95]:
df.head()

,歩数,摂取カロリー
date,,
2024-11-01,5439,2500.0
2024-11-02,2510,2300.0
2024-11-03,10238,1950.0
2024-11-04,8209,1850.0
2024-11-05,9434,1930.0


In [96]:
df['歩数/カロリー'] = (df['歩数']/df['摂取カロリー'])
df.head()

,歩数,摂取カロリー,歩数/カロリー
date,,,
2024-11-01,5439,2500.0,2.175600
2024-11-02,2510,2300.0,1.091304
2024-11-03,10238,1950.0,5.250256
2024-11-04,8209,1850.0,4.437297
2024-11-05,9434,1930.0,4.888083


In [99]:
def exercise_judge(ex):
    if ex <= 3.0:
        return 'Low'
    elif ex <= 6.0:
        return 'Mid'
    else:
        return 'High'

df['運動指数'] = df.loc[:, '歩数/カロリー'].apply(exercise_judge)
df.head()

,歩数,摂取カロリー,歩数/カロリー,運動指数
date,,,,
2024-11-01,5439,2500.0,2.175600,Low
2024-11-02,2510,2300.0,1.091304,Low
2024-11-03,10238,1950.0,5.250256,Mid
2024-11-04,8209,1850.0,4.437297,Mid
2024-11-05,9434,1930.0,4.888083,Mid


In [100]:
df.to_pickle('data/202411health.pickle')