#以前までの復習
##numpy pandasの復習

In [ ]:
#一次元配列の作成
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [4]:
#二次元配列の作成
b=np.array([[1,2,3],[4,5,6]])
print(b)
type(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#変形 reshape
c1=np.array([0,1,2,3,4,5])
print(c1)
c2=c1.reshape((2,3))
print(c2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
c3=c2.ravel()   #ravelは参照を返す
print(c3)
c4=c2.flatten()  #flattenはコピーを返す
c4

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

In [ ]:
#データ型について  numpy配列の要素は一つのデータ型に統一される
a.dtype

dtype('int64')

In [8]:
#データ型の宣言、変更
d=np.array([1,2], dtype=np.int16)
d.dtype

dtype('int16')

In [9]:
#astypeメソッドで変換
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [10]:
#行列のインデックス
b[0]

array([1, 2, 3])

In [11]:
#二行一列の数値を指定
b[1,0]

np.int64(4)

In [12]:
b[:,0]

array([1, 4])

In [13]:
b[0,:]

array([1, 2, 3])

In [ ]:
#インデックス値が飛んでいる場合、リストでインデックスを渡す
b[0,[0,2]] #一行目一列、三列目の指定

array([1, 3])

In [15]:
#データ再代入
print(a)
a[2]= 4 
print(a)

[1 2 3]
[1 2 4]


In [16]:
b[1,2]=7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [18]:
b[:,2]=8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [ ]:
np.arange(10)

In [2]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#乱数生成
rng=np.random.default_rng()   #rngはインスタント
f=rng.random((3,2))
f

array([[0.62065414, 0.1476412 ],
       [0.02410416, 0.23722025],
       [0.04352203, 0.42859189]])

In [5]:
rng=np.random.default_rng(123)
rng.integers(1,10)

np.int64(1)

In [7]:
rng=np.random.default_rng(123)
rng.integers(1,10,size=(3,3))

array([[1, 7, 6],
       [1, 9, 2],
       [3, 2, 4]])

In [8]:
rng=np.random.default_rng(123)
rng.uniform(0.0,5.0,size=(2,3))


array([[3.41175932, 0.26910509, 1.10179936],
       [0.92185905, 0.87952951, 4.06047253]])

In [9]:
rng=np.random.default_rng(123)
rng.uniform(size=(4,3))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451],
       [0.923345  , 0.2765744 , 0.81975456],
       [0.88989269, 0.51297046, 0.2449646 ]])

In [10]:
#正規分布
rng=np.random.default_rng(123)
rng.standard_normal(size=(4,2))   #平均０、分散１の正規分布　　normal=正規？

array([[-0.98912135, -0.36778665],
       [ 1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379],
       [-0.63646365,  0.54195222]])

In [ ]:
rng=np.random.default_rng(123)
rng.normal(50,10,3)

array([40.1087865 , 46.32213349, 62.87925261])

In [14]:
#同じ要素の数列の作成
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)  #単位行列

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.full(3,3.14)

array([3.14, 3.14, 3.14])

In [18]:
np.full((3,2),np.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
#連結、分割、転置
a=np.array([1,5,4])
a1=np.array([1,5,4])
np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [23]:
b=np.array([[1,2,8],[4,5,8]])
b1=np.array([[10],[20]])
print(b)
print(b1)
np.concatenate([b,b1],axis=1)

[[1 2 8]
 [4 5 8]]
[[10]
 [20]]


array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [24]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [25]:
b2=np.array([30,60,45])
b3=np.vstack([b,b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [27]:
first,second=np.hsplit(b3,[2])
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [28]:
first1,second1=np.vsplit(b3,[2])
print(first1,second1)

[[1 2 8]
 [4 5 8]] [[30 60 45]]


In [29]:
print(b)
b.T

[[1 2 8]
 [4 5 8]]


array([[1, 4],
       [2, 5],
       [8, 8]])

In [ ]:
#次元追加
print(a)
a[np.newaxis,:]

[1 5 4]


array([[1, 5, 4]])

In [32]:
#ユニバーサルファンクション,ブロードキャスト
li=np.array([[-3,-2,1],[2,-9,-4]])
print(li)
np.abs(li)

[[-3 -2  1]
 [ 2 -9 -4]]


array([[3, 2, 1],
       [2, 9, 4]])

In [34]:
print(a)
a+10

[1 5 4]


array([11, 15, 14])

In [35]:
#配列の掛け算
np.dot(b,a)

array([43, 61])

In [36]:
b@a

array([43, 61])

In [ ]:
a>1   #判定　真偽値が同じ形状の配列で出力

array([False,  True,  True])