ベトナム旅行、研究室引っ越し、調査、入院で期間がとても空いてしまった
夏休み中に資格を取り切りたい
24に予約したからあと１０日で仕上げる
いったんは復習

In [1]:
l = [x**x for x in range(100)]
type(l), len(l)

(list, 100)

In [7]:
g = (x**x for x in range(100))
type(g)

generator

In [8]:
next(g)

1

In [4]:
next(g)

1

In [5]:
next(g)

4

In [9]:
s = '  spam ham eggs  '
s.split()

['spam', 'ham', 'eggs']

In [11]:
s.strip()

'spam ham eggs'

In [12]:
s3 = 'sample.jpg'
s3.endswith(('jpg', 'gif', 'png'))


True

In [13]:
s3.removeprefix('sample')

'.jpg'

In [14]:
s3.removesuffix('.jpg')

'sample'

In [15]:
'123'.isdigit()

True

In [16]:
'='.join(['spam', 'ham', 'eggs'])


'spam=ham=eggs'

In [19]:
' and '.join(['spam', 'ham', 'eggs'])

'spam and ham and eggs'

In [ ]:
%timeit -n 1000 -r 10 [x**x for x in range(100)]  # %から始まるコマンドをマジックコマンド　%timeitは一行のプログラムの実行時間を複数回計測するコマンド　

65.5 μs ± 3.32 μs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [ ]:
%%timeit -n 1000 -r 10    # %%timeitはセル全体  内包表記のほうが処理時間が短いことが分かる
ret = []
for x in range(100):
    ret.append(x**x)

69.4 μs ± 7.72 μs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [28]:
!pip list # ! の後にOSコマンドでシェルコマンドの実行が可能　pip list で仮想環境にインストールされたパッケージの一覧を表示

Package                           Version
--------------------------------- --------------------
aext-assistant                    4.20.0
aext-assistant-server             4.20.0
aext-core                         4.20.0
aext-core-server                  4.20.0
aext_environments_server          4.20.0
aext-panels                       4.20.0
aext-panels-server                4.20.0
aext-project-filebrowser-server   4.20.0
aext-share-notebook               4.20.0
aext-share-notebook-server        4.20.0
aext-shared                       4.20.0
aext-toolbox                      4.20.0
aiobotocore                       2.25.0
aiodns                            3.5.0
aiohappyeyeballs                  2.6.1
aiohttp                           3.13.2
aioitertools                      0.12.0
aiosignal                         1.4.0
alabaster                         0.7.16
alembic                           1.18.0
altair                            5.5.0
anaconda-anon-usage               0.7.5
anacon

In [29]:
#numpy
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [30]:
type(a)

numpy.ndarray

In [31]:
a.shape

(3,)

In [32]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
type(b), b.shape

(numpy.ndarray, (2, 3))

In [34]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [36]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [37]:
a.dtype

dtype('int64')

In [38]:
d = np.array([1, 2], dtype='int16')
print(d)
d.dtype

[1 2]


dtype('int16')

In [39]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [40]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [41]:
rng = np.random.default_rng(123)
f = rng.random((3, 2))
f

array([[0.68235186, 0.05382102],
       [0.22035987, 0.18437181],
       [0.1759059 , 0.81209451]])

In [42]:
rng.integers(1, 10)

np.int64(5)

In [43]:
rng.integers(1, 10, size=(3, 3))

array([[9, 5, 3],
       [8, 8, 8],
       [9, 1, 5]])

In [ ]:
rng.uniform(0.0, 5.0, size=(3, 4)) #rng.randomはゼロ以上1未満　uniformは範囲指定可　引数省略でrandomと同じ

array([[1.22482301, 4.12120798, 1.06881482, 3.70733526],
       [3.14970102, 4.63703629, 1.15954094, 3.99562564],
       [2.59082518, 1.15777812, 0.82951997, 2.48894484]])

In [45]:
rng.standard_normal(size=(4, 2))

array([[ 1.12680679,  0.75476964],
       [-0.14597789,  1.28190223],
       [ 1.07403062,  0.39262084],
       [ 0.00511431, -0.36176687]])

In [46]:
rng.normal(50, 10, 3)

array([37.69767805, 62.26229293, 28.27956113])

In [48]:
np.zeros(3)

array([0., 0., 0.])

In [50]:
np.full(3, np.pi)

array([3.14159265, 3.14159265, 3.14159265])

In [51]:
np.nan

nan

In [52]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [56]:
#連結
print(a)
a1 = a
a1

[1 2 3]


array([1, 2, 3])

In [58]:
np.concatenate([a, a1])

array([1, 2, 3, 1, 2, 3])

In [59]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [61]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [ ]:
np.hstack([b, b1]) #こっちのほうが楽やな

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [63]:
b2 = np.array([30, 60, 45])
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [64]:
first, second = np.hsplit(b3, [2])
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [65]:
first1, second1 = np.vsplit(b3, [2])
first1

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a

array([1, 2, 3])

In [68]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [69]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [70]:
np.dot(b, a)

array([14, 32])

In [71]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a

array([1, 2, 3])

In [73]:
b@a

array([14, 32])

In [74]:
a > 1

array([False,  True,  True])

In [75]:
a[a>1]

array([2, 3])

In [76]:
(a>1).astype(int)

array([0, 1, 1])

In [77]:
np.count_nonzero(a>1)

np.int64(2)

In [78]:
np.any(b > 0)

np.True_

In [81]:
np.all(b > 1)

np.False_

In [80]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
np.count_nonzero(a == b)

np.int64(3)

In [83]:
a == b

array([[ True,  True,  True],
       [False, False, False]])

In [84]:
import pandas  as pd
ser = pd.Series([10, 20, 30, 40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
df = pd.Dataframe