#以前までの復習
##numpy pandasの復習

In [ ]:
#一次元配列の作成
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [4]:
#二次元配列の作成
b=np.array([[1,2,3],[4,5,6]])
print(b)
type(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#変形 reshape
c1=np.array([0,1,2,3,4,5])
print(c1)
c2=c1.reshape((2,3))
print(c2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
c3=c2.ravel()   #ravelは参照を返す
print(c3)
c4=c2.flatten()  #flattenはコピーを返す
c4

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

In [ ]:
#データ型について  numpy配列の要素は一つのデータ型に統一される
a.dtype

dtype('int64')

In [8]:
#データ型の宣言、変更
d=np.array([1,2], dtype=np.int16)
d.dtype

dtype('int16')

In [9]:
#astypeメソッドで変換
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [10]:
#行列のインデックス
b[0]

array([1, 2, 3])

In [11]:
#二行一列の数値を指定
b[1,0]

np.int64(4)

In [12]:
b[:,0]

array([1, 4])

In [13]:
b[0,:]

array([1, 2, 3])

In [ ]:
#インデックス値が飛んでいる場合、リストでインデックスを渡す
b[0,[0,2]] #一行目一列、三列目の指定

array([1, 3])

In [15]:
#データ再代入
print(a)
a[2]= 4 
print(a)

[1 2 3]
[1 2 4]


In [16]:
b[1,2]=7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [18]:
b[:,2]=8
b

array([[1, 2, 8],
       [4, 5, 8]])